In [1]:
import pandas as pd
df=pd.read_csv('/content/car_price_performance.csv')

In [2]:
df

        Brand  Price  Horsepower  Fuel Efficiency
0     Brand C  91942         382             15.3
1     Brand A  70075         197             32.6
2     Brand C  84524         188             34.9
3     Brand E  68939         258             15.1
4     Brand X  66505         277             13.0
...       ...    ...         ...              ...
1995  Brand Z  34535         196             15.2
1996  Brand C  35215         377             25.3
1997  Brand E  72980         294             21.8
1998  Brand Z  55921         443             11.0
1999  Brand B  95051         225             12.4

[2000 rows x 4 columns]

In [3]:
df.columns

Index(['Brand', 'Price', 'Horsepower', 'Fuel Efficiency'], dtype='object')

In [5]:
nullpricedata=df[df['Price'].isna()]
nullpricedata

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [6]:
brand_avg_prices = df.groupby("Brand")["Price"].mean().sort_values()
brand_avg_prices

Brand
Brand W    63034.557018
Brand E    63712.542601
Brand Y    63880.171569
Brand A    64224.495370
Brand B    64686.641350
Brand C    64707.967890
Brand Z    65244.331818
Brand X    65405.884259
Brand D    65498.701681
Name: Price, dtype: float64

In [7]:
d = {}
count = 1

for i in brand_avg_prices.index:
    d[i] = count
    count += 1

print(d)

{'Brand W': 1, 'Brand E': 2, 'Brand Y': 3, 'Brand A': 4, 'Brand B': 5, 'Brand C': 6, 'Brand Z': 7, 'Brand X': 8, 'Brand D': 9}

In [8]:
x = []

for j in df["Brand"]:
    y = d[j]
    x.append(y)
df["Encoded Brand"]=x
df

        Brand  Price  Horsepower  Fuel Efficiency  Encoded Brand
0     Brand C  91942         382             15.3              6
1     Brand A  70075         197             32.6              4
2     Brand C  84524         188             34.9              6
3     Brand E  68939         258             15.1              2
4     Brand X  66505         277             13.0              8
...       ...    ...         ...              ...            ...
1995  Brand Z  34535         196             15.2              7
1996  Brand C  35215         377             25.3              6
1997  Brand E  72980         294             21.8              2
1998  Brand Z  55921         443             11.0              7
1999  Brand B  95051         225             12.4              5

[2000 rows x 5 columns]

In [9]:
scaledhp=(df["Horsepower"]-df["Horsepower"].min())/(df["Horsepower"].max()-df["Horsepower"].min())
scaledhp

0       0.7050
1       0.2425
2       0.2200
3       0.3950
4       0.4425
         ...
1995    0.2400
1996    0.6925
1997    0.4850
1998    0.8575
1999    0.3125
Name: Horsepower, Length: 2000, dtype: float64

In [13]:
df['scaled horsepower'] =scaledhp
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded Brand,scaled horsepower,scaled fuel efficiency
0,Brand C,91942,382,15.3,6,0.7050,0.212
1,Brand A,70075,197,32.6,4,0.2425,0.904
2,Brand C,84524,188,34.9,6,0.2200,0.996
3,Brand E,68939,258,15.1,2,0.3950,0.204
4,Brand X,66505,277,13.0,8,0.4425,0.120
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208
1996,Brand C,35215,377,25.3,6,0.6925,0.612
1997,Brand E,72980,294,21.8,2,0.4850,0.472
1998,Brand Z,55921,443,11.0,7,0.8575,0.040
1999,Brand B,95051,225,12.4,5,0.3125,0.096

In [11]:
scaledfe=(df["Fuel Efficiency"]-df["Fuel Efficiency"].min())/(df["Fuel Efficiency"].max()-df["Fuel Efficiency"].min())
scaledfe

0       0.212
1       0.904
2       0.996
3       0.204
4       0.120
        ...
1995    0.208
1996    0.612
1997    0.472
1998    0.040
1999    0.096
Name: Fuel Efficiency, Length: 2000, dtype: float64

In [12]:
df['scaled fuel efficiency'] =scaledfe
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded Brand,scaled horsepower,scaled fuel efficiency
0,Brand C,91942,382,15.3,6,0.7050,0.212
1,Brand A,70075,197,32.6,4,0.2425,0.904
2,Brand C,84524,188,34.9,6,0.2200,0.996
3,Brand E,68939,258,15.1,2,0.3950,0.204
4,Brand X,66505,277,13.0,8,0.4425,0.120
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208
1996,Brand C,35215,377,25.3,6,0.6925,0.612
1997,Brand E,72980,294,21.8,2,0.4850,0.472
1998,Brand Z,55921,443,11.0,7,0.8575,0.040
1999,Brand B,95051,225,12.4,5,0.3125,0.096

In [14]:
scaledbrand=(df["Encoded Brand"]-df["Encoded Brand"].min())/(df["Encoded Brand"].max()-df["Encoded Brand"].min())
scaledbrand

0       0.625
1       0.375
2       0.625
3       0.125
4       0.875
        ...
1995    0.750
1996    0.625
1997    0.125
1998    0.750
1999    0.500
Name: Encoded Brand, Length: 2000, dtype: float64

In [15]:
df['scaled brand'] =scaledbrand
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded Brand,scaled horsepower,scaled fuel efficiency,scaled brand
0,Brand C,91942,382,15.3,6,0.7050,0.212,0.625
1,Brand A,70075,197,32.6,4,0.2425,0.904,0.375
2,Brand C,84524,188,34.9,6,0.2200,0.996,0.625
3,Brand E,68939,258,15.1,2,0.3950,0.204,0.125
4,Brand X,66505,277,13.0,8,0.4425,0.120,0.875
...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208,0.750
1996,Brand C,35215,377,25.3,6,0.6925,0.612,0.625
1997,Brand E,72980,294,21.8,2,0.4850,0.472,0.125
1998,Brand Z,55921,443,11.0,7,0.8575,0.040,0.750
1999,Brand B,95051,225,12.4,5,0.3125,0.096,0.500

In [16]:
df['Performance Index'] = ((df['Horsepower'] * 0.7) + (df['Fuel Efficiency'] * 0.3)) / df['Price']
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded Brand,scaled horsepower,scaled fuel efficiency,scaled brand,Performance Index
0,Brand C,91942,382,15.3,6,0.7050,0.212,0.625,0.002958
1,Brand A,70075,197,32.6,4,0.2425,0.904,0.375,0.002107
2,Brand C,84524,188,34.9,6,0.2200,0.996,0.625,0.001681
3,Brand E,68939,258,15.1,2,0.3950,0.204,0.125,0.002685
4,Brand X,66505,277,13.0,8,0.4425,0.120,0.875,0.002974
...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208,0.750,0.004105
1996,Brand C,35215,377,25.3,6,0.6925,0.612,0.625,0.007709
1997,Brand E,72980,294,21.8,2,0.4850,0.472,0.125,0.002910
1998,Brand Z,55921,443,11.0,7,0.8575,0.040,0.750,0.005604
1999,Brand B,95051,225,12.4,5,0.3125,0.096,0.500,0.001696

In [17]:
df.to_csv('full_car_performance_analysis.csv', index=False)

from google.colab import files
files.download('full_car_performance_analysis.csv')